name: hermes-picotin-monitor
services:
- name: picotin-monitor
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/hermez
  build_command: npm install
  run_command: npm run start:picotin
  instance_size_slug: basic-xxs
  instance_count: 1
  envs:
  - key: TWILIO_ACCOUNT_SID
    scope: RUN_TIME
    value: ${TWILIO_ACCOUNT_SID}
  - key: TWILIO_AUTH_TOKEN
    scope: RUN_TIME
    value: ${TWILIO_AUTH_TOKEN}
  - key: TWILIO_PHONE_NUMBER
    scope: RUN_TIME
    value: ${TWILIO_PHONE_NUMBER}
  - key: TEST_RECIPIENT_NUMBER
    scope: RUN_TIME
    value: ${TEST_RECIPIENT_NUMBER}
  - key: MONITOR_INTERVAL_MINUTES
    scope: RUN_TIME
    value: "5"
  - key: MONITOR_BUSINESS_HOURS_ONLY
    scope: RUN_TIME
    value: "true"
  - key: MONITOR_START_HOUR
    scope: RUN_TIME
    value: "9"
  - key: MONITOR_END_HOUR
    scope: RUN_TIME
    value: "18"
  - key: MONITOR_WEEKDAYS_ONLY
    scope: RUN_TIME
    value: "true"