name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 143.198.41.150
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/apps/hermes
          git pull origin main
          npm install
          pm2 restart picotin-monitor
          pm2 save